### ISSUE TITLE
Internet interface

### ISSUE THREAD

**Issue by micro222** [micro222/chatbot#4]
I'd like the chatbot to be accessible from the internet, either on IRC or the web

**Comment by philparadis** [comment]
Great idea! I think setting up an IRC bot is probably the easiest way to go and completely free.

**Comment by micro222** [comment]
I wrote a test program in LUA that worked. Maybe that'll help

**Comment by philparadis** [comment]
What about the chatbot having access to the Web? I.e., being able to pull up the current news from an RSS feeds and transform the news header into a sentence like "Did you hear about <topic> which happened <at that time> in <location>?".

**Comment by micro222** [comment]
As long as the robot can understand the news items.

**Comment by philparadis** [comment]
That's exiting! I'm working on a NoSQL database to complement the existing
.txt databases, which will help easily perform  search between related
items and more importantly, it has the capacity to grow to very large scale
since it is designed to be extremely efficient and it uses compression for
disk storage. In other words, we could have a more knowledgeable bot.

Btw, sorry I haven't been able to contribute much, I've been particularly
busy. Do you wanna go for drone photoshoots on Sunday? It's supposed to be
sunny.

**Comment by micro222** [comment]
The IRC interface is now implemented. I'll upload soon.

**Comment by micro222** [comment]
Now uploaded. Go to webchat.freenode.net/ and join "chatbot".

Hey Phil, I sent you an email last week. I was wondering how you were doing. Did you receive it?
